
-- KSP Manager Stage 2 Clean Migration
-- Run in Supabase SQL Editor.
-- Safe for existing tables: columns/policies are added only when missing.

alter table public.nasabah add column if not exists nomor_anggota varchar(5);
alter table public.nasabah add column if not exists credit_score integer default 5;
alter table public.nasabah add column if not exists status text default 'aktif';

do $$ begin
  alter table public.nasabah add constraint nasabah_nomor_anggota_format check (nomor_anggota is null or nomor_anggota ~ '^[0-9]{1,5}$');
exception when duplicate_object then null; end $$;
do $$ begin
  alter table public.nasabah add constraint nasabah_credit_score_range check (credit_score between 0 and 10);
exception when duplicate_object then null; end $$;

alter table public.pengajuan_kredit add column if not exists model_jatuh_tempo text default 'mingguan';
alter table public.pinjaman add column if not exists model_jatuh_tempo text default 'mingguan';

alter table public.angsuran add column if not exists angsuran_pokok numeric default 0;
alter table public.angsuran add column if not exists angsuran_murni numeric default 0;
alter table public.angsuran add column if not exists pelunasan numeric default 0;
alter table public.angsuran add column if not exists total numeric default 0;
alter table public.angsuran add column if not exists titip_angsuran numeric default 0;
alter table public.angsuran add column if not exists saldo numeric default 0;
alter table public.angsuran add column if not exists tanggal_bayar date;
alter table public.angsuran add column if not exists jumlah_dibayar numeric default 0;
alter table public.angsuran add column if not exists status text default 'belum_bayar';

create table if not exists public.ledger_harian (
  id bigint generated by default as identity primary key,
  nomor integer generated by default as identity unique,
  tanggal date not null default current_date,
  nomor_anggota varchar(5) not null,
  nama text not null,
  alamat text not null,
  drop_lama numeric not null default 0,
  drop_baru numeric not null default 0,
  bht numeric not null default 0,
  materai numeric not null default 0,
  staf_nama text,
  created_at timestamptz not null default now()
);

alter table public.ledger_harian add column if not exists staf_nama text;
alter table public.ledger_harian add column if not exists created_at timestamptz not null default now();

-- Automatic status check: inactive after 3 months without a new loan.
create or replace function public.ksp_sync_nasabah_status()
returns void language plpgsql security definer set search_path=public as $$
begin
  update public.nasabah n
  set status='nonaktif'
  where coalesce(lower(n.status),'aktif')='aktif'
    and not exists (
      select 1 from public.pinjaman p
      where p.nasabah_id=n.id
        and coalesce(p.created_at,p.tanggal_mulai) >= (current_date - interval '3 months')
    )
    and exists (select 1 from public.pinjaman p2 where p2.nasabah_id=n.id);
end $$;

-- Keep existing score; new rows start at a neutral score of 5.
alter table public.nasabah alter column credit_score set default 5;

-- Demo/client-side session architecture requires data policies.
alter table public.ledger_harian enable row level security;
do $$ begin
  create policy "ksp ledger select" on public.ledger_harian for select to anon, authenticated using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "ksp ledger insert" on public.ledger_harian for insert to anon, authenticated with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "ksp ledger update" on public.ledger_harian for update to anon, authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;

-- Helpful read/write policies for newly used fields if the existing project
-- does not already have permissive policies.
do $$ begin
  create policy "ksp nasabah select" on public.nasabah for select to anon, authenticated using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "ksp nasabah insert" on public.nasabah for insert to anon, authenticated with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "ksp nasabah update" on public.nasabah for update to anon, authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "ksp pengajuan select" on public.pengajuan_kredit for select to anon, authenticated using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "ksp pengajuan insert" on public.pengajuan_kredit for insert to anon, authenticated with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "ksp pengajuan update" on public.pengajuan_kredit for update to anon, authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "ksp pinjaman select" on public.pinjaman for select to anon, authenticated using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "ksp pinjaman insert" on public.pinjaman for insert to anon, authenticated with check (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "ksp angsuran select" on public.angsuran for select to anon, authenticated using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "ksp angsuran insert" on public.angsuran for insert to anon, authenticated with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "ksp angsuran update" on public.angsuran for update to anon, authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;
